# Generated by Django 3.1.6 on 2021-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_system', '0006_auto_20210216_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default=1, upload_to='BlogsImage'),
            preserve_default=False,
        ),
    ]
