# Generated by Django 3.1.6 on 2021-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_system', '0007_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=1, upload_to='PostsImage'),
            preserve_default=False,
        ),
    ]
