# Generated by Django 3.1.6 on 2021-02-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_system', '0009_auto_20210223_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(null=True, upload_to='BlogsImage'),
        ),
    ]
