# Generated by Django 3.1.6 on 2021-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_system', '0010_auto_20210223_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='PostsImage'),
        ),
    ]
